Function1FightCount = 0
TypeSelect = 0
systemUnlock = " "
capture = None
DCBOT_Token = '0000'
DCBOT_ChannalID = 0
DCBOT_EN = False
locations = []
StepDelay = 0
RoundDelay = 0
P1X = 0
P1Y = 0
P2X = 0
P2Y = 0
P3X = 0
P3Y = 0
P4X = 0
P4Y = 0
RandomX = 0
NRandomX = 0
RandomY = 0
NRandomY = 0
BroswerText = " "
HTML_Text = "https://game.granbluefantasy.jp/#top"
WindowsHandle = 0

RunFlag = False
StopFunction = False