Function1FightCount = 0
TypeSelect = 0
systemUnlock = " "
capture = None
DCBOT_Token = '0000'
DCBOT_ChannalID = 0
DCBOT_EN = False
locations = []
StepDelay = 0
RoundDelay = 0
P1X = 0
P1Y = 0
P2X = 0
P2Y = 0
P3X = 0
P3Y = 0
P4X = 0
P4Y = 0
P5X = 0
P5Y = 0
P6X = 0
P6Y = 0
RandomX = 0
NRandomX = 0
RandomY = 0
NRandomY = 0
stepdelayRandom = 0
NstepdelayRandom = 0
RounddelayRandom = 0
NRounddelayRandom = 0
BroswerText = " "
WindowsHandle = 0
CurmoveTime = 0
CurmoveTimeRan = 0
NCurmoveTimeRan = 0

RunFlag = False
StopFunction = False
version = '星爆螞蟻人 V0.1.3'